import {z} from 'zod';
import {JobRequirements, SimplifiedJobRequirements} from './domain';
import {simplifiedJobDomainKeyToTableKey} from '../job';
import {simplifiedJobRequirementTypeDomainKeyToTableKey} from '../job-requirement-type/database';
import {KeyTranslator} from '../../services/filters/where-filter';

/**
 * Simplified job requirements row shape - base fields in snake_case (includes id, excludes timestamps)
 * Database row equivalent of SimplifiedJobRequirements
 */
export const simplifiedJobRequirementsRowShape = {
    id: z.uuidv4(),
    job_id: z.uuidv4(),
    job_requirement_type_id: z.number().int().positive(),
    criteria: z.record(z.string(), z.unknown()),
    priority: z.number().int(),
};

/**
 * Simplified job requirements row schema (snake_case, includes id, excludes timestamps)
 * Database row equivalent of SimplifiedJobRequirements
 */
export const simplifiedJobRequirementsRowSchema = z.object(simplifiedJobRequirementsRowShape);

export type SimplifiedJobRequirementsRow = z.infer<typeof simplifiedJobRequirementsRowSchema>;

/**
 * Database row schema for job_requirements table (snake_case)
 * Used for validating data coming from the database
 */
export const jobRequirementsRowSchema = simplifiedJobRequirementsRowSchema.extend({
    created_at: z.date(),
    updated_at: z.date(),
});

export type JobRequirementsRow = z.infer<typeof jobRequirementsRowSchema>;

export const jobRequirementsDomainKeyToTableKey: KeyTranslator<JobRequirements> = {
    id: 'id',
    criteria: 'criteria' as any,
    priority: 'priority',
    job: simplifiedJobDomainKeyToTableKey,
    jobRequirementType: simplifiedJobRequirementTypeDomainKeyToTableKey,
    createdAt: 'created_at',
    updatedAt: 'updated_at',
};

export const simplifiedJobRequirementsDomainKeyToTableKey: KeyTranslator<SimplifiedJobRequirements> = {
    id: 'id',
    jobId: 'job_id',
    requirementTypeId: 'job_requirement_type_id',
    criteria: 'criteria' as any,
    priority: 'priority',
};

/**
 * Database row schema for inserting a new job requirement (snake_case)
 * Excludes id and timestamps which are generated by the database
 */
export const insertJobRequirementsRowSchema = z.object({
    job_id: z.uuidv4(),
    job_requirement_type_id: z.number().int().positive(),
    criteria: z.record(z.string(), z.unknown()),
    priority: z.number().int(),
});

export type InsertJobRequirementsRow = z.infer<typeof insertJobRequirementsRowSchema>;

