import {z} from 'zod';
import {QueryResult} from 'pg';
import {JobRequirements, SimplifiedJobRequirements} from './domain';
import {simplifiedJobDomainKeyToTableKey} from '../job';
import {simplifiedJobRequirementTypeDomainKeyToTableKey} from '../job-requirement-type/database';
import {KeyTranslator} from '../../services/filters/where-filter';

/**
 * Simplified job requirements row shape - base fields in snake_case (includes id, excludes timestamps)
 * Database row equivalent of SimplifiedJobRequirements
 */
export const simplifiedJobRequirementsRowShape = {
    id: z.uuidv4(),
    job_id: z.uuidv4(),
    job_requirement_type_id: z.number().int().positive(),
    criteria: z.record(z.string(), z.unknown()),
    priority: z.number().int(),
};

/**
 * Simplified job requirements row schema (snake_case, includes id, excludes timestamps)
 * Database row equivalent of SimplifiedJobRequirements
 */
export const simplifiedJobRequirementsRowSchema = z.object(simplifiedJobRequirementsRowShape);

export type SimplifiedJobRequirementsRow = z.infer<typeof simplifiedJobRequirementsRowSchema>;

/**
 * Database row schema for job_requirements table (snake_case)
 * Used for validating data coming from the database
 */
export const jobRequirementsRowSchema = simplifiedJobRequirementsRowSchema.extend({
    created_at: z.date(),
    updated_at: z.date(),
});

export type JobRequirementsRow = z.infer<typeof jobRequirementsRowSchema>;

export const jobRequirementsDomainKeyToTableKey: KeyTranslator<JobRequirements> = {
    id: 'id',
    criteria: 'criteria' as any,
    priority: 'priority',
    job: simplifiedJobDomainKeyToTableKey,
    jobRequirementType: simplifiedJobRequirementTypeDomainKeyToTableKey,
    createdAt: 'created_at',
    updatedAt: 'updated_at',
};

export const simplifiedJobRequirementsDomainKeyToTableKey: KeyTranslator<SimplifiedJobRequirements> = {
    id: 'id',
    jobId: 'job_id',
    requirementTypeId: 'job_requirement_type_id',
    criteria: 'criteria' as any,
    priority: 'priority',
};

/**
 * Database row schema for inserting a new job requirement (snake_case)
 * Excludes id and timestamps which are generated by the database
 */
export const insertJobRequirementsRowSchema = z.object({
    job_id: z.uuidv4(),
    job_requirement_type_id: z.number().int().positive(),
    criteria: z.record(z.string(), z.unknown()),
    priority: z.number().int(),
});

export type InsertJobRequirementsRow = z.infer<typeof insertJobRequirementsRowSchema>;

/**
 * Gets job requirement IDs for a job (ordered by priority).
 * 
 * @param client - Database client (can be from a transaction or pool)
 * @param jobId - The job ID
 * @returns Array of job requirement IDs, ordered by priority and creation date
 * @throws Error if no job requirements found
 */
export const getJobRequirementIds = async (
  client: { query: (text: string, values?: unknown[]) => Promise<QueryResult> },
  jobId: string
): Promise<string[]> => {
  const query = `
    SELECT id
    FROM job_requirements
    WHERE job_id = $1
    ORDER BY priority ASC, created_at ASC
  `;
  
  const result: QueryResult<{ id: string }> = await client.query(query, [jobId]);
  
  if (result.rows.length === 0) {
    throw new Error(`No job requirements found for job: ${jobId}`);
  }
  
  return result.rows.map(row => row.id);
};

