import {z} from 'zod';
import {Message} from './domain';
import {simplifiedConversationDomainKeyToTableKey} from '../conversation/database';
import {messageSenderSchema} from '../enums';
import {KeyTranslator} from '../../services/filters/where-filter';

/**
 * Database row schema for message table (snake_case)
 * Used for validating data coming from the database
 */
export const messageRowSchema = z.object({
    id: z.uuidv4(),
    conversation_id: z.uuidv4(),
    sender: messageSenderSchema,
    content: z.string(),
    created_at: z.date(),
});

export type MessageRow = z.infer<typeof messageRowSchema>;

export const messageDomainKeyToTableKey: KeyTranslator<Message> = {
    id: 'id',
    sender: 'sender',
    content: 'content',
    createdAt: 'created_at',
    conversation: simplifiedConversationDomainKeyToTableKey,
};

/**
 * Database row schema for inserting a new message (snake_case)
 * Excludes id and timestamps which are generated by the database
 */
export const insertMessageRowSchema = z.object({
    conversation_id: z.uuidv4(),
    sender: messageSenderSchema,
    content: z.string(),
});

export type InsertMessageRow = z.infer<typeof insertMessageRowSchema>;

