import {z} from 'zod';
import {QueryResult} from 'pg';
import {Message} from './domain';
import {simplifiedConversationDomainKeyToTableKey} from '../conversation/database';
import {messageSenderSchema, MessageSender} from '../enums';
import {KeyTranslator} from '../../services/filters/where-filter';

/**
 * Database row schema for message table (snake_case)
 * Used for validating data coming from the database
 */
export const messageRowSchema = z.object({
    id: z.uuidv4(),
    conversation_id: z.uuidv4(),
    sender: messageSenderSchema,
    content: z.string(),
    created_at: z.date(),
});

export type MessageRow = z.infer<typeof messageRowSchema>;

export const messageDomainKeyToTableKey: KeyTranslator<Message> = {
    id: 'id',
    sender: 'sender',
    content: 'content',
    createdAt: 'created_at',
    conversation: simplifiedConversationDomainKeyToTableKey,
};

/**
 * Database row schema for inserting a new message (snake_case)
 * Excludes id and timestamps which are generated by the database
 */
export const insertMessageRowSchema = z.object({
    conversation_id: z.uuidv4(),
    sender: messageSenderSchema,
    content: z.string(),
});

export type InsertMessageRow = z.infer<typeof insertMessageRowSchema>;

/**
 * Creates a new message in the database.
 * 
 * @param client - Database client (can be from a transaction or pool)
 * @param conversationId - The conversation ID this message belongs to
 * @param sender - The message sender (USER, ASSISTANT, SYSTEM)
 * @param content - The message content
 * @returns The created message ID
 */
export const createMessage = async (
  client: { query: (text: string, values?: unknown[]) => Promise<QueryResult> },
  conversationId: string,
  sender: MessageSender,
  content: string
): Promise<string> => {
  const query = `
    INSERT INTO message (id, conversation_id, sender, content)
    VALUES (gen_random_uuid(), $1, $2, $3)
    RETURNING id
  `;
  
  const insertData = insertMessageRowSchema.parse({
    conversation_id: conversationId,
    sender,
    content,
  });
  
  const result: QueryResult<{ id: string }> = await client.query(query, [
    insertData.conversation_id,
    insertData.sender,
    insertData.content,
  ]);
  
  return result.rows[0].id;
};

