import {z} from 'zod';
import {Address, addressKeySchema, addressSchema} from "./domain";

/**
 * Simplified address row shape - base fields in snake_case (includes id, excludes timestamps)
 * Database row equivalent of SimplifiedAddress
 */
export const simplifiedAddressRowShape = {
    id: z.uuidv4(),
    city: z.string(),
    address: z.string().nullable(),
    apt_number: z.string().nullable(),
    state: z.string().max(2).nullable(),
    zip_code: z.string().nullable(),
};

/**
 * Simplified address row schema (snake_case, includes id, excludes timestamps)
 * Database row equivalent of SimplifiedAddress
 */
export const simplifiedAddressRowSchema = z.object(simplifiedAddressRowShape);

export type SimplifiedAddressRow = z.infer<typeof simplifiedAddressRowSchema>;

/**
 * Database row schema for address table (snake_case)
 * Used for validating data coming from the database
 */
export const addressRowSchema = simplifiedAddressRowSchema.extend({
    created_at: z.date(),
    updated_at: z.date(),
});

export type AddressRow = z.infer<typeof addressRowSchema>;
export const addressDomainKeyToTableKey: Record<keyof Address, string> = {
    id: 'id',
    address: 'address',
    city: 'city',
    aptNumber: 'apt_number',
    state: 'state',
    zipCode: 'zip_code',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
}

export const domainToDatabaseKey = (key: string, translator: Record<keyof Address, keyof AddressRow>): keyof AddressRow => {
    const domainKey = addressSchema.keyof().parse(key);
    return translator[domainKey];
}
/**
 * Database row schema for inserting a new address (snake_case)
 * Excludes id and timestamps which are generated by the database
 */
export const insertAddressRowSchema = z.object({
    address: z.string().nullable(),
    apt_number: z.string().nullable(),
    state: z.string().max(2).nullable(),
    zip_code: z.string().nullable(),
});

export type InsertAddressRow = z.infer<typeof insertAddressRowSchema>;

