import {z} from 'zod';
import {JobFactsType, SimplifiedJobFactsType} from './domain';
import {KeyTranslator} from '../../services/filters/where-filter';

/**
 * Simplified job facts type row shape - base fields in snake_case (includes id, excludes timestamps)
 * Database row equivalent of SimplifiedJobFactsType
 */
export const simplifiedJobFactsTypeRowShape = {
    id: z.number().int().positive(),
    fact_type: z.string().max(50),
    fact_description: z.string(),
};

/**
 * Simplified job facts type row schema (snake_case, includes id, excludes timestamps)
 * Database row equivalent of SimplifiedJobFactsType
 */
export const simplifiedJobFactsTypeRowSchema = z.object(simplifiedJobFactsTypeRowShape);

export type SimplifiedJobFactsTypeRow = z.infer<typeof simplifiedJobFactsTypeRowSchema>;

/**
 * Database row schema for job_facts_type table (snake_case)
 * Used for validating data coming from the database
 */
export const jobFactsTypeRowSchema = simplifiedJobFactsTypeRowSchema.extend({
    created_at: z.date(),
    updated_at: z.date(),
});

export type JobFactsTypeRow = z.infer<typeof jobFactsTypeRowSchema>;

export const jobFactsTypeDomainKeyToTableKey: KeyTranslator<JobFactsType> = {
    id: 'id',
    factType: 'fact_type',
    factDescription: 'fact_description',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
};

export const simplifiedJobFactsTypeDomainKeyToTableKey: KeyTranslator<SimplifiedJobFactsType> = {
    id: 'id',
    factType: 'fact_type',
    factDescription: 'fact_description',
};

/**
 * Database row schema for inserting a new job facts type (snake_case)
 * Excludes id and timestamps which are generated by the database
 */
export const insertJobFactsTypeRowSchema = z.object({
    fact_type: z.string().max(50),
    fact_description: z.string(),
});

export type InsertJobFactsTypeRow = z.infer<typeof insertJobFactsTypeRowSchema>;


