import {z} from 'zod';
import {JobFacts, SimplifiedJobFacts} from './domain';
import {simplifiedJobDomainKeyToTableKey} from '../job/database';
import {simplifiedJobFactsTypeDomainKeyToTableKey} from '../job-facts-type/database';
import {KeyTranslator} from '../../services/filters/where-filter';

/**
 * Simplified job facts row shape - base fields in snake_case (includes id, excludes timestamps)
 * Database row equivalent of SimplifiedJobFacts
 */
export const simplifiedJobFactsRowShape = {
    id: z.uuidv4(),
    job_id: z.uuidv4(),
    fact_type_id: z.number().int().positive(),
    content: z.string(),
};

/**
 * Simplified job facts row schema (snake_case, includes id, excludes timestamps)
 * Database row equivalent of SimplifiedJobFacts
 */
export const simplifiedJobFactsRowSchema = z.object(simplifiedJobFactsRowShape);

export type SimplifiedJobFactsRow = z.infer<typeof simplifiedJobFactsRowSchema>;

/**
 * Database row schema for job_facts table (snake_case)
 * Used for validating data coming from the database
 */
export const jobFactsRowSchema = simplifiedJobFactsRowSchema.extend({
    created_at: z.date(),
    updated_at: z.date(),
});

export type JobFactsRow = z.infer<typeof jobFactsRowSchema>;

export const jobFactsDomainKeyToTableKey: KeyTranslator<JobFacts> = {
    id: 'id',
    content: 'content',
    job: simplifiedJobDomainKeyToTableKey,
    factType: simplifiedJobFactsTypeDomainKeyToTableKey,
    createdAt: 'created_at',
    updatedAt: 'updated_at',
};

export const simplifiedJobFactsDomainKeyToTableKey: KeyTranslator<SimplifiedJobFacts> = {
    id: 'id',
    jobId: 'job_id',
    factTypeId: 'fact_type_id',
    content: 'content',
};

/**
 * Database row schema for inserting a new job fact (snake_case)
 * Excludes id and timestamps which are generated by the database
 */
export const insertJobFactsRowSchema = z.object({
    job_id: z.uuidv4(),
    fact_type_id: z.number().int().positive(),
    content: z.string(),
});

export type InsertJobFactsRow = z.infer<typeof insertJobFactsRowSchema>;

