import {z} from 'zod';
import {ConversationRequirements} from './domain';
import {requirementStatusSchema} from '../enums';
import {KeyTranslator} from '../../services/filters/where-filter';
import {conversationDomainKeyToTableKey} from '../conversation';
import { jobRequirementsDomainKeyToTableKey } from '../job-requirements';

/**
 * Database row schema for conversation_requirements table (snake_case)
 * Used for validating data coming from the database
 */
export const conversationRequirementsRowSchema = z.object({
    conversation_id: z.uuidv4(),
    requirement_id: z.uuidv4(),
    message_id: z.uuidv4().nullable(),
    status: requirementStatusSchema,
    value: z.record(z.string(), z.unknown()).nullable(),
    last_updated: z.date(),
    created_at: z.date(),
});

export type ConversationRequirementsRow = z.infer<typeof conversationRequirementsRowSchema>;

export const conversationRequirementsDomainKeyToTableKey: KeyTranslator<ConversationRequirements> = {
    id: "id",
    conversation: conversationDomainKeyToTableKey,
    jobRequirements: jobRequirementsDomainKeyToTableKey,
    messageId: 'message_id',
    status: 'status',
    value: 'value',
    lastUpdated: 'last_updated',
    createdAt: 'created_at'
};

/**
 * Database row schema for inserting a new conversation requirement (snake_case)
 * Excludes timestamps which are generated by the database
 */
export const insertConversationRequirementsRowSchema = z.object({
    conversation_id: z.uuidv4(),
    requirement_id: z.uuidv4(),
    message_id: z.uuidv4().nullable().optional(),
    status: requirementStatusSchema.optional(),
    value: z.record(z.string(), z.unknown()).nullable().optional(),
});

export type InsertConversationRequirementsRow = z.infer<typeof insertConversationRequirementsRowSchema>;


