import {z} from 'zod';
import {QueryResult} from 'pg';
import {Application, SimplifiedApplication} from './domain';
import {simplifiedUserDomainKeyToTableKey} from '../user/database';
import {simplifiedJobDomainKeyToTableKey} from '../job/database';
import {applicationStatusSchema} from '../enums';
import {KeyTranslator} from '../../services/filters/where-filter';

/**
 * Simplified application row shape - base fields in snake_case (includes id, excludes timestamps)
 * Database row equivalent of SimplifiedApplication
 */
export const simplifiedApplicationRowShape = {
    id: z.uuidv4(),
    user_id: z.uuidv4(),
    job_id: z.uuidv4(),
    applied_on: z.date(),
    status: applicationStatusSchema,
};

/**
 * Simplified application row schema (snake_case, includes id, excludes timestamps)
 * Database row equivalent of SimplifiedApplication
 */
export const simplifiedApplicationRowSchema = z.object(simplifiedApplicationRowShape);

export type SimplifiedApplicationRow = z.infer<typeof simplifiedApplicationRowSchema>;

/**
 * Database row schema for application table (snake_case)
 * Used for validating data coming from the database
 */
export const applicationRowSchema = simplifiedApplicationRowSchema.extend({
    created_at: z.date(),
    updated_at: z.date(),
});

export type ApplicationRow = z.infer<typeof applicationRowSchema>;

export const applicationDomainKeyToTableKey: KeyTranslator<Application> = {
    id: 'id',
    appliedOn: 'applied_on',
    status: 'status',
    user: simplifiedUserDomainKeyToTableKey,
    job: simplifiedJobDomainKeyToTableKey,
    createdAt: 'created_at',
    updatedAt: 'updated_at',
};

export const simplifiedApplicationDomainKeyToTableKey: KeyTranslator<SimplifiedApplication> = {
    id: 'id',
    userId: 'user_id',
    jobId: 'job_id',
    appliedOn: 'applied_on',
    status: 'status',
};

/**
 * Database row schema for inserting a new application (snake_case)
 * Excludes id and timestamps which are generated by the database
 */
export const insertApplicationRowSchema = z.object({
    user_id: z.uuidv4(),
    job_id: z.uuidv4(),
    applied_on: z.date().optional(),
    status: applicationStatusSchema.optional(),
});

export type InsertApplicationRow = z.infer<typeof insertApplicationRowSchema>;

/**
 * Result type for application data with related job and user information.
 * Used when querying application with joins to job and users tables.
 */
export interface ApplicationWithJobAndUser {
  jobId: string;
  jobName: string;
  userFirstName: string;
}

/**
 * Gets application data with related job and user information.
 * 
 * @param client - Database client (can be from a transaction or pool)
 * @param applicationId - The application ID
 * @returns Application data with job ID, job name, and user first name
 * @throws Error if application not found
 */
export const getApplicationWithJobAndUser = async (
  client: { query: (text: string, values?: unknown[]) => Promise<QueryResult> },
  applicationId: string
): Promise<ApplicationWithJobAndUser> => {
  const query = `
    SELECT 
      a.job_id as jobId,
      j.name as jobName,
      u.first_name as userFirstName
    FROM application a
    INNER JOIN job j ON a.job_id = j.id
    INNER JOIN users u ON a.user_id = u.id
    WHERE a.id = $1
  `;
  
  const result: QueryResult<ApplicationWithJobAndUser> = await client.query(query, [applicationId]);
  
  if (result.rows.length === 0) {
    throw new Error(`Application not found: ${applicationId}`);
  }
  
  const {jobId, jobName, userFirstName} = result.rows[0];
  return { jobId, jobName, userFirstName };
};

