import {z} from 'zod';
import {Application, SimplifiedApplication} from './domain';
import {simplifiedUserDomainKeyToTableKey} from '../user/database';
import {simplifiedJobDomainKeyToTableKey} from '../job/database';
import {applicationStatusSchema} from '../enums';
import {KeyTranslator} from '../../services/filters/where-filter';

/**
 * Simplified application row shape - base fields in snake_case (includes id, excludes timestamps)
 * Database row equivalent of SimplifiedApplication
 */
export const simplifiedApplicationRowShape = {
    id: z.uuidv4(),
    user_id: z.uuidv4(),
    job_id: z.uuidv4(),
    applied_on: z.date(),
    status: applicationStatusSchema,
};

/**
 * Simplified application row schema (snake_case, includes id, excludes timestamps)
 * Database row equivalent of SimplifiedApplication
 */
export const simplifiedApplicationRowSchema = z.object(simplifiedApplicationRowShape);

export type SimplifiedApplicationRow = z.infer<typeof simplifiedApplicationRowSchema>;

/**
 * Database row schema for application table (snake_case)
 * Used for validating data coming from the database
 */
export const applicationRowSchema = simplifiedApplicationRowSchema.extend({
    created_at: z.date(),
    updated_at: z.date(),
});

export type ApplicationRow = z.infer<typeof applicationRowSchema>;

export const applicationDomainKeyToTableKey: KeyTranslator<Application> = {
    id: 'id',
    appliedOn: 'applied_on',
    status: 'status',
    user: simplifiedUserDomainKeyToTableKey,
    job: simplifiedJobDomainKeyToTableKey,
    createdAt: 'created_at',
    updatedAt: 'updated_at',
};

export const simplifiedApplicationDomainKeyToTableKey: KeyTranslator<SimplifiedApplication> = {
    id: 'id',
    userId: 'user_id',
    jobId: 'job_id',
    appliedOn: 'applied_on',
    status: 'status',
};

/**
 * Database row schema for inserting a new application (snake_case)
 * Excludes id and timestamps which are generated by the database
 */
export const insertApplicationRowSchema = z.object({
    user_id: z.uuidv4(),
    job_id: z.uuidv4(),
    applied_on: z.date().optional(),
    status: applicationStatusSchema.optional(),
});

export type InsertApplicationRow = z.infer<typeof insertApplicationRowSchema>;

