import {z} from 'zod';
import {JobRequirementType, SimplifiedJobRequirementType} from './domain';
import {KeyTranslator} from '../../services/filters/where-filter';

/**
 * Simplified job requirement type row shape - base fields in snake_case (includes id, excludes timestamps)
 * Database row equivalent of SimplifiedJobRequirementType
 */
export const simplifiedJobRequirementTypeRowShape = {
    id: z.number().int().positive(),
    requirement_type: z.string().max(50),
    requirement_description: z.string(),
};

/**
 * Simplified job requirement type row schema (snake_case, includes id, excludes timestamps)
 * Database row equivalent of SimplifiedJobRequirementType
 */
export const simplifiedJobRequirementTypeRowSchema = z.object(simplifiedJobRequirementTypeRowShape);

export type SimplifiedJobRequirementTypeRow = z.infer<typeof simplifiedJobRequirementTypeRowSchema>;

/**
 * Database row schema for job_requirement_type table (snake_case)
 * Used for validating data coming from the database
 */
export const jobRequirementTypeRowSchema = simplifiedJobRequirementTypeRowSchema.extend({
    created_at: z.date(),
    updated_at: z.date(),
});

export type JobRequirementTypeRow = z.infer<typeof jobRequirementTypeRowSchema>;

export const jobRequirementTypeDomainKeyToTableKey: KeyTranslator<JobRequirementType> = {
    id: 'id',
    requirementType: 'requirement_type',
    requirementDescription: 'requirement_description',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
};

export const simplifiedJobRequirementTypeDomainKeyToTableKey: KeyTranslator<SimplifiedJobRequirementType> = {
    id: 'id',
    requirementType: 'requirement_type',
    requirementDescription: 'requirement_description',
};

/**
 * Database row schema for inserting a new job requirement type (snake_case)
 * Excludes id and timestamps which are generated by the database
 */
export const insertJobRequirementTypeRowSchema = z.object({
    requirement_type: z.string().max(50),
    requirement_description: z.string(),
});

export type InsertJobRequirementTypeRow = z.infer<typeof insertJobRequirementTypeRowSchema>;


