import {z} from 'zod';
import {Job, SimplifiedJob, jobKeySchema, jobSchema} from './domain';
import {addressDomainKeyToTableKey} from '../address';
import {paymentTypeSchema} from '../enums';
import {KeyTranslator} from '../../services/filters/where-filter';

/**
 * Simplified job row shape - base fields in snake_case (includes id, excludes timestamps)
 * Database row equivalent of SimplifiedJob
 */
export const simplifiedJobRowShape = {
    id: z.uuidv4(),
    name: z.string(),
    description: z.string(),
    payment_type: paymentTypeSchema,
    hourly_pay: z.number().nullable(),
    miles_pay: z.number().nullable(),
    salary_pay: z.number().nullable(),
    address_id: z.uuidv4(),
    is_active: z.boolean(),
};

/**
 * Simplified job row schema (snake_case, includes id, excludes timestamps)
 * Database row equivalent of SimplifiedJob
 */
export const simplifiedJobRowSchema = z.object(simplifiedJobRowShape);

export type SimplifiedJobRow = z.infer<typeof simplifiedJobRowSchema>;

/**
 * Database row schema for job table (snake_case)
 * Used for validating data coming from the database
 */
export const jobRowSchema = simplifiedJobRowSchema.extend({
    created_at: z.date(),
    updated_at: z.date(),
});

export type JobRow = z.infer<typeof jobRowSchema>;

export const simplifiedJobDomainKeyToTableKey: KeyTranslator<SimplifiedJob> = {
    id: 'id',
    name: 'name',
    description: 'description',
    paymentType: 'payment_type',
    hourlyPay: 'hourly_pay',
    milesPay: 'miles_pay',
    salaryPay: 'salary_pay',
    addressId: 'address_id',
    isActive: 'is_active',
};

export const jobDomainKeyToTableKey: KeyTranslator<Job> = {
    id: 'id',
    name: 'name',
    description: 'description',
    paymentType: 'payment_type',
    hourlyPay: 'hourly_pay',
    milesPay: 'miles_pay',
    salaryPay: 'salary_pay',
    address: addressDomainKeyToTableKey,
    isActive: 'is_active',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
};


/**
 * Database row schema for inserting a new job (snake_case)
 * Excludes id and timestamps which are generated by the database
 */
export const insertJobRowSchema = z.object({
    name: z.string(),
    description: z.string(),
    payment_type: paymentTypeSchema,
    hourly_pay: z.number().nullable(),
    miles_pay: z.number().nullable(),
    salary_pay: z.number().nullable(),
    address_id: z.uuidv4(),
    is_active: z.boolean(),
});

export type InsertJobRow = z.infer<typeof insertJobRowSchema>;

